/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/groups/join`; params?: Router.UnknownInputParams; } | { pathname: `/groups/new`; params?: Router.UnknownInputParams; } | { pathname: `/groups/[groupId]`, params: Router.UnknownInputParams & { groupId: string | number; } } | { pathname: `/groups/[groupId]/bets/[betId]`, params: Router.UnknownInputParams & { groupId: string | number;betId: string | number; } } | { pathname: `/groups/[groupId]/bets/new`, params: Router.UnknownInputParams & { groupId: string | number; } } | { pathname: `/invite/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/groups/join`; params?: Router.UnknownOutputParams; } | { pathname: `/groups/new`; params?: Router.UnknownOutputParams; } | { pathname: `/groups/[groupId]`, params: Router.UnknownOutputParams & { groupId: string; } } | { pathname: `/groups/[groupId]/bets/[betId]`, params: Router.UnknownOutputParams & { groupId: string;betId: string; } } | { pathname: `/groups/[groupId]/bets/new`, params: Router.UnknownOutputParams & { groupId: string; } } | { pathname: `/invite/[code]`, params: Router.UnknownOutputParams & { code: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/groups/join${`?${string}` | `#${string}` | ''}` | `/groups/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/groups/join`; params?: Router.UnknownInputParams; } | { pathname: `/groups/new`; params?: Router.UnknownInputParams; } | `/groups/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/groups/${Router.SingleRoutePart<T>}/bets/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/groups/${Router.SingleRoutePart<T>}/bets/new${`?${string}` | `#${string}` | ''}` | `/invite/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/groups/[groupId]`, params: Router.UnknownInputParams & { groupId: string | number; } } | { pathname: `/groups/[groupId]/bets/[betId]`, params: Router.UnknownInputParams & { groupId: string | number;betId: string | number; } } | { pathname: `/groups/[groupId]/bets/new`, params: Router.UnknownInputParams & { groupId: string | number; } } | { pathname: `/invite/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
    }
  }
}
