"""add email notification preferences to users

Revision ID: c67c8e928c0c
Revises: 369be0577cf6
Create Date: 2026-03-02 16:27:30.627940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67c8e928c0c'
down_revision: Union[str, Sequence[str], None] = '369be0577cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_bet_created', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('email_wager_placed', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('email_bet_resolved', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_bet_resolved')
        batch_op.drop_column('email_wager_placed')
        batch_op.drop_column('email_bet_created')

    # ### end Alembic commands ###
